# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master, develop, github-actions ]
  pull_request:
    branches: [ master, develop, github-actions ]

jobs:
  build:

    runs-on: ubuntu-bionic

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install os dependencies
      run: | 
        sudo apt-get update
        sudo apt-get -y install gfortran swig
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python setup.py egg_info
        pip install -r photonai.egg-info/requires.txt
        pip install -r photonai/optimization/smac/smac_requirements.txt
        pip install tensorflow
        pip install pytest
        pip install pytest-cov
        pip install coveralls
    - name: Test with pytest
      run: |
        PYTHONPATH=./ pytest ./test --cov=./photonai
